"""1: add dedup_key idempotency column to activities

Revision ID: b3d9f1a7c2e4
Revises: c7d8e9f0a1b2
Create Date: 2026-07-21 00:00:00.000000

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b3d9f1a7c2e4"
down_revision: str | None = "c7d8e9f0a1b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the dedup_key idempotency column to activities.
    op.add_column(
        "activities",
        sa.Column(
            "dedup_key",
            sa.String(length=255),
            nullable=True,
            comment="Stable idempotency key (provider id or content hash) to no-op re-imports",
        ),
    )

    # Backfill provider-scoped keys for existing rows so re-imports of already
    # ingested provider activities are recognised as duplicates. Strava takes
    # precedence over Garmin, matching the ingestion-service derivation order.
    op.execute(
        "UPDATE activities SET dedup_key = 'strava:' || CAST(strava_activity_id AS VARCHAR) "
        "WHERE strava_activity_id IS NOT NULL AND dedup_key IS NULL"
    )
    op.execute(
        "UPDATE activities SET dedup_key = 'garmin:' || CAST(garminconnect_activity_id AS VARCHAR) "
        "WHERE garminconnect_activity_id IS NOT NULL AND dedup_key IS NULL"
    )

    op.create_index(op.f("ix_activities_dedup_key"), "activities", ["dedup_key"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activities_dedup_key"), table_name="activities")
    op.drop_column("activities", "dedup_key")
    # ### end Alembic commands ###
