"""3: sync event_log/followers column comments and add missing followers.id index

Revision ID: 95e5558ce7a2
Revises: a7f3c1e9d2b4
Create Date: 2026-07-24 12:38:11.189039

Autogenerated diff aligning the database with model-only changes: refreshed
column comments on ``event_log.status`` and ``followers.follower_id`` /
``followers.followee_id`` / ``followers.status`` to match their current
docstrings, and added the missing explicit ``ix_followers_id`` index (the
``id`` surrogate primary key added in migration 2 relies on the implicit
``followers_pkey`` index alone; the model additionally declares
``index=True``).

The autogenerate diff also proposed dropping ``idx_event_log_metadata`` (the
GIN index on ``event_log.event_metadata``). That has been removed from this
migration: the index is intentionally NOT declared on the SQLAlchemy model
(see ``infra/event_log/models.py`` — GIN indexes aren't representable in a
dialect-agnostic ``Table`` since SQLite can't build them) but it does exist in
the database, so autogenerate will always flag it as "extra" and propose
dropping it. Do not reintroduce that drop/recreate here or in future
autogenerated migrations.
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "95e5558ce7a2"
down_revision: str | None = "a7f3c1e9d2b4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.alter_column(
        "event_log",
        "status",
        existing_type=sa.VARCHAR(length=20),
        comment="published | queued | processing | completed | failed | dead_letter",
        existing_comment="published | processing | completed | failed | dead_letter",
        existing_nullable=False,
        existing_server_default=sa.text("'published'::character varying"),
    )
    op.alter_column(
        "followers",
        "follower_id",
        existing_type=sa.INTEGER(),
        comment="ID of the follower user (the requester)",
        existing_comment="ID of the follower user",
        existing_nullable=False,
    )
    op.alter_column(
        "followers",
        "followee_id",
        existing_type=sa.INTEGER(),
        comment="ID of the followee user (the target being followed)",
        existing_comment="ID of the following user",
        existing_nullable=False,
    )
    op.alter_column(
        "followers",
        "status",
        existing_type=sa.VARCHAR(length=20),
        comment="Follow request status: pending or accepted",
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.create_index(op.f("ix_followers_id"), "followers", ["id"], unique=False)


def downgrade() -> None:
    op.drop_index(op.f("ix_followers_id"), table_name="followers")
    op.alter_column(
        "followers",
        "status",
        existing_type=sa.VARCHAR(length=20),
        comment=None,
        existing_comment="Follow request status: pending or accepted",
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.alter_column(
        "followers",
        "followee_id",
        existing_type=sa.INTEGER(),
        comment="ID of the following user",
        existing_comment="ID of the followee user (the target being followed)",
        existing_nullable=False,
    )
    op.alter_column(
        "followers",
        "follower_id",
        existing_type=sa.INTEGER(),
        comment="ID of the follower user",
        existing_comment="ID of the follower user (the requester)",
        existing_nullable=False,
    )
    op.alter_column(
        "event_log",
        "status",
        existing_type=sa.VARCHAR(length=20),
        comment="published | processing | completed | failed | dead_letter",
        existing_comment="published | queued | processing | completed | failed | dead_letter",
        existing_nullable=False,
        existing_server_default=sa.text("'published'::character varying"),
    )
