"""add health_intraday_steps table and add health_intraday_heart_rate table

Revision ID: 8a1de728bc73
Revises: 262ec21a6c15
Create Date: 2026-01-25 21:01:55.539661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a1de728bc73'
down_revision: Union[str, None] = '262ec21a6c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_intraday_heart_rate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User ID that the health_steps belongs'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='Health intraday heart rates timestamp (datetime)'),
    sa.Column('heart_rate', sa.Integer(), nullable=False, comment='Heart rate measurment (bpm)'),
    sa.Column('source', sa.String(length=250), nullable=True, comment='Source of the health heart rate data'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'timestamp', name='uq_user_timestamp_health_intraday_heart_rate')
    )
    op.create_index(op.f('ix_health_intraday_heart_rate_timestamp'), 'health_intraday_heart_rate', ['timestamp'], unique=False)
    op.create_index(op.f('ix_health_intraday_heart_rate_user_id'), 'health_intraday_heart_rate', ['user_id'], unique=False)
    op.create_table('health_intraday_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User ID that the health_intraday_steps belongs'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='Health intraday steps timestamp (datetime)'),
    sa.Column('steps', sa.Integer(), nullable=False, comment='Cumulative number of steps taken'),
    sa.Column('distance', sa.Float(), nullable=True, comment='Cumulative distance traveled'),
    sa.Column('source', sa.String(length=250), nullable=True, comment='Source of the health steps data'),
    sa.Column('activity_type', sa.Integer(), nullable=True, comment='Activity type'),
    sa.Column('intensity', sa.Integer(), nullable=True, comment='Intensity'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'timestamp', name='uq_user_timestamp_health_intraday_steps')
    )
    op.create_index(op.f('ix_health_intraday_steps_timestamp'), 'health_intraday_steps', ['timestamp'], unique=False)
    op.create_index(op.f('ix_health_intraday_steps_user_id'), 'health_intraday_steps', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_intraday_steps_user_id'), table_name='health_intraday_steps')
    op.drop_index(op.f('ix_health_intraday_steps_timestamp'), table_name='health_intraday_steps')
    op.drop_table('health_intraday_steps')
    op.drop_index(op.f('ix_health_intraday_heart_rate_user_id'), table_name='health_intraday_heart_rate')
    op.drop_index(op.f('ix_health_intraday_heart_rate_timestamp'), table_name='health_intraday_heart_rate')
    op.drop_table('health_intraday_heart_rate')
    # ### end Alembic commands ###
