"""Add onelapfit_region field to users_integrations table

Revision ID: 5c0g1a9d4e3f
Revises: 4b9g0f8c3d2e
Create Date: 2026-03-25 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c0g1a9d4e3f'
down_revision: Union[str, None] = '4b9g0f8c3d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_integrations', sa.Column('onelapfit_region', sa.VARCHAR(length=10), nullable=True, comment='OneLapFit region code'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_integrations', 'onelapfit_region')
    # ### end Alembic commands ###
