"""Add OneLapFit integration support

Revision ID: 3a8f9e7b2c1d
Revises: 262ec21a6c15
Create Date: 2026-03-20 15:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a8f9e7b2c1d'
down_revision: Union[str, None] = '262ec21a6c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_integrations', sa.Column('onelapfit_token', sa.VARCHAR(length=512), nullable=True, comment='Encrypted OneLapFit authentication token'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_integrations', 'onelapfit_token')
    # ### end Alembic commands ###
