"""add_routes_schema

Revision ID: 81b2383c2748
Revises: 262ec21a6c15
Create Date: 2026-03-13 16:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "81b2383c2748"
down_revision: Union[str, None] = "262ec21a6c15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "routes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
            comment="User ID that owns this route",
        ),
        sa.Column(
            "name", sa.String(length=255), nullable=False, comment="Name of the route"
        ),
        sa.Column(
            "description", sa.Text(), nullable=True, comment="Description of the route"
        ),
        sa.Column(
            "activity_type",
            sa.String(length=50),
            nullable=False,
            comment="Type of activity (e.g., cycling, running)",
        ),
        sa.Column(
            "sub_type",
            sa.String(length=50),
            nullable=True,
            comment="Sub-type (e.g., gravel, road, trail)",
        ),
        sa.Column(
            "distance",
            sa.Float(),
            nullable=False,
            comment="Total distance in meters",
        ),
        sa.Column(
            "elevation_gain",
            sa.Float(),
            nullable=True,
            comment="Total elevation gain in meters",
        ),
        sa.Column(
            "route_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="JSON structure containing waypoints and full coordinate path",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When the route was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When the route was last updated",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_routes_id"), "routes", ["id"], unique=False)
    op.create_index(op.f("ix_routes_user_id"), "routes", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_routes_user_id"), table_name="routes")
    op.drop_index(op.f("ix_routes_id"), table_name="routes")
    op.drop_table("routes")
    # ### end Alembic commands ###
