"""Add onelapfit_id field to activities table

Revision ID: 4b9g0f8c3d2e
Revises: 3a8f9e7b2c1d
Create Date: 2026-03-21 11:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b9g0f8c3d2e'
down_revision: Union[str, None] = '3a8f9e7b2c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('onelapfit_id', sa.VARCHAR(length=255), nullable=True, comment='OneLapFit activity ID'))
    op.create_unique_constraint('uq_activities_onelapfit_id', 'activities', ['onelapfit_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_activities_onelapfit_id', 'activities', type_='unique')
    op.drop_column('activities', 'onelapfit_id')
    # ### end Alembic commands ###
